"""Generate office documents (currently the Project Information Sheet).

Uses python-docx to produce a real, editable Word document. The exact layout is
a first draft - once we have her existing Project Information Sheet we will match
it field-for-field.
"""

from __future__ import annotations

import os
from typing import Dict, List, Tuple

try:
    from docx import Document
    from docx.shared import Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    _DOCX_OK = True
except Exception:  # pragma: no cover
    _DOCX_OK = False


class DocError(Exception):
    """A user-friendly document-generation problem."""


def _require_docx() -> None:
    if not _DOCX_OK:
        raise DocError(
            "The Word engine (python-docx) is not installed.\n"
            "Reinstall the app, or run: pip install python-docx"
        )


# Fields shown on the Project Information Sheet, in order.
# (label, config/info key)
PROJECT_INFO_FIELDS: List[Tuple[str, str]] = [
    ("Project Number", "number"),
    ("Project Name", "name"),
    ("Client", "client"),
    ("Client Contact", "client_contact"),
    ("Client Phone", "client_phone"),
    ("Client Email", "client_email"),
    ("Project Address", "address"),
    ("Project Type", "project_type"),
    ("Engineer / PM", "engineer"),
    ("Drafter", "drafter"),
    ("Date Opened", "date_opened"),
    ("Proposal Date", "proposal_date"),
    ("Fee", "fee"),
    ("Notes", "notes"),
]


def generate_project_info_sheet(
    dest_path: str,
    info: Dict[str, str],
    company_name: str = "",
) -> str:
    """Write a Project Information Sheet .docx to ``dest_path``. Returns the path."""
    _require_docx()
    os.makedirs(os.path.dirname(os.path.abspath(dest_path)) or ".", exist_ok=True)

    doc = Document()

    if company_name:
        head = doc.add_paragraph()
        head.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = head.add_run(company_name)
        run.bold = True
        run.font.size = Pt(16)

    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    trun = title.add_run("Project Information Sheet")
    trun.bold = True
    trun.font.size = Pt(14)
    trun.font.color.rgb = RGBColor(0x1F, 0x4E, 0x79)

    doc.add_paragraph()  # spacer

    table = doc.add_table(rows=0, cols=2)
    table.style = "Light Grid Accent 1"
    for label, key in PROJECT_INFO_FIELDS:
        row = table.add_row().cells
        lab = row[0].paragraphs[0].add_run(label)
        lab.bold = True
        row[0].width = Pt(150)
        row[1].text = str(info.get(key, "") or "")

    doc.add_paragraph()
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    frun = footer.add_run("Generated by KBEARWERK")
    frun.italic = True
    frun.font.size = Pt(8)
    frun.font.color.rgb = RGBColor(0x80, 0x80, 0x80)

    doc.save(dest_path)
    return dest_path
